name: METAR-archive-cookbook
channels:
  - conda-forge
dependencies:
  - python>=3.14
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - duckdb
  - geopandas
  - metpy
  - lonboard
  - s3fs
  - zarr
  - dask 
  - seaborn
  - vim
  - intake
  - intake-parquet
  - intake-xarray
  - pgeocode
  - pandas
  - numpy
  - hvplot
  - holoviews
  - shapely
  - ipywidgets
  - palettable
  - sidecar
  - geodatasets
  - geopy
